/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.aspa_menu;

/**
 *
 * @author Ryan Dave
 */
public class NewJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewJFrame.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtSnacksQty = new javax.swing.JTextField();
        txtDrinks = new javax.swing.JTextField();
        txtDrinkQty = new javax.swing.JTextField();
        txtSnacks = new javax.swing.JTextField();
        btnProcced = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnChange = new javax.swing.JButton();
        txtChange = new javax.swing.JTextField();
        txtSubtot = new javax.swing.JTextField();
        txtCash = new javax.swing.JTextField();
        btnOrder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("FOOD ORDER SYSTEM");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setText("MENU");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("DRINKS:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel4.setText("1.Coke     P20");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel5.setText("2.Sprite    P25");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setText("SNACKS:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel7.setText("1.Fries     P25");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel8.setText("2.Burger   P30");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel9.setText("QUANTITY:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));
        jPanel1.add(txtSnacksQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 140, 30));
        jPanel1.add(txtDrinks, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 140, 30));
        jPanel1.add(txtDrinkQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 140, 30));
        jPanel1.add(txtSnacks, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 140, 30));

        btnProcced.setText("PROCCED");
        btnProcced.addActionListener(this::btnProccedActionPerformed);
        jPanel1.add(btnProcced, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 120, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 390, 350));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setText("PAYMENT");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel11.setText("Sub Total:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel12.setText("Cash:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        btnChange.setText("Change");
        btnChange.addActionListener(this::btnChangeActionPerformed);
        jPanel2.add(btnChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 80, 30));
        jPanel2.add(txtChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 130, 30));
        jPanel2.add(txtSubtot, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 130, 30));
        jPanel2.add(txtCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 130, 30));

        btnOrder.setText("ORDER AGAIN");
        btnOrder.addActionListener(this::btnOrderActionPerformed);
        jPanel2.add(btnOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 210, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 250, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProccedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProccedActionPerformed
String drink = txtDrinks.getText();
    int drinkQty = Integer.parseInt(txtDrinkQty.getText());

    String snack = txtSnacks.getText();
    int snackQty = Integer.parseInt(txtSnacksQty.getText());

    int drinkPrice = 0;
    int snackPrice = 0;

    // Drinks
    if (drink.equals("1")) {
        drinkPrice = 20;   
    } else if (drink.equals("2")) {
        drinkPrice = 25;   
    }

    // Snacks
    if (snack.equals("1")) {
        snackPrice = 25;   
    } else if (snack.equals("2")) {
        snackPrice = 30;   
    }

    int subtotal = (drinkPrice * drinkQty) 
                 + (snackPrice * snackQty);

    txtSubtot.setText(String.valueOf(subtotal));          // TODO add your handling code here:
    }//GEN-LAST:event_btnProccedActionPerformed

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
    double subtotal = Double.parseDouble(txtSubtot.getText());
    double cash = Double.parseDouble(txtCash.getText());

    double change = cash - subtotal;

    txtChange.setText(String.valueOf(change));         // TODO add your handling code here:
    }//GEN-LAST:event_btnChangeActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
    txtDrinks.setText("");
    txtDrinkQty.setText("");
    txtSnacks.setText("");
    txtSnacksQty.setText("");
    txtSubtot.setText("");
    txtCash.setText("");
    txtChange.setText("");

    txtDrinks.requestFocus();          // TODO add your handling code here:
    }//GEN-LAST:event_btnOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NewJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnProcced;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtCash;
    private javax.swing.JTextField txtChange;
    private javax.swing.JTextField txtDrinkQty;
    private javax.swing.JTextField txtDrinks;
    private javax.swing.JTextField txtSnacks;
    private javax.swing.JTextField txtSnacksQty;
    private javax.swing.JTextField txtSubtot;
    // End of variables declaration//GEN-END:variables
}
